version: '3'
services:
  api_rails:
    build: .
    command: rails s -b 0.0.0.0 -p 4000
    container_name: api_rails_container_1
    ports:
      - 4000:4000
    volumes:
      - .:/opt/app
    networks:
      - new_api_network
networks:
  new_api_network:
    external:
      name: 'external-net'
