version: '3'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: api_charge_first_container
    ports:
      - 3100:3000
      - 4100:4000
    volumes:
      - .:/opt/app